services:
  promobot:
    build: .
    container_name: promobot_container
    volumes:
      - ./data:/app/data
      - ./logs:/app/logs
    env_file:
      - .env
    restart: unless-stopped
    shm_size: '2gb'
